
version: '3.8'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    networks:
      - my-network

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    networks:
      - my-network

  app:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - redis
      - mongo
    restart: always
    networks:
      - my-network

networks:
  my-network: